PROJECT_SECRET_KEY = "Enter your secret key"
EMAIL_HOST_USER = "Enter your SMTP server host user name"
EMAIL_HOST_PASSWORD = 'Enter your SMTP host password'
SENDER_EMAIL = "Enter your sender email id"
REPLY_EMAIL = "Enter your reply email id"
PRODUCTION_URL = "Enter your Production url"
DB_NAME = 'Enter your Database Name'
DB_USER = 'Enter your database username'
DB_PASS = 'Enter your database password'
DB_HOST = 'Enter your database host IP'
DB_PORT = 'Enter your database port number'
