"""
Django settings for sbhs_server project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from sbhs_server import credentials

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Set this variable to <False> once the project is in production.
# If this variable is kept <True> in production, email will not be verified.
IS_DEVELOPMENT=True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/sudo cat /var/log/auth.log | grep "session opened for user root"howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = credentials.PROJECT_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'sbhs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sbhs_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sbhs_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

if not IS_DEVELOPMENT:
    DATABASES = {
            'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': credentials.DB_NAME,
            'USER': credentials.DB_USER,
            'PASSWORD': credentials.DB_PASS,
            'HOST': credentials.DB_HOST,
            'PORT': credentials.DB_PORT,
        }
       }
else:
    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
         }
       }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

SLOT_DURATION = 59
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'experiments/')

EMAIL_USE_TLS = True

EMAIL_HOST = 'Write SMTP Server Email ID'

EMAIL_PORT = 25

EMAIL_HOST_USER = credentials.EMAIL_HOST_USER

EMAIL_HOST_PASSWORD = credentials.EMAIL_HOST_PASSWORD

# Set EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend'
# in production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SENDER_EMAIL, REPLY_EMAIL, PRODUCTION_URL, IS_DEVELOPMENT are used in email
# verification. Set the variables accordingly to avoid errors in production

# This email id will be used as <from address> for sending emails.
# For example no_reply@<your_organization>.in can be used.
SENDER_EMAIL = credentials.SENDER_EMAIL

# Organisation/Indivudual Name.
SENDER_NAME = 'SBHS Team'

# This email id will be used by users to send their queries
# For example queries@<your_organization>.in can be used.
REPLY_EMAIL = credentials.REPLY_EMAIL

# This url will be used in email verification to create activation link.
# Add your hosted url to this variable.
# For example https://127.0.0.1:8000 or 127.0.0.1:8000
PRODUCTION_URL = credentials.PRODUCTION_URL


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SBHS_API_IPS = []
 
# for e.g 127.0.0.1:1234
# Enter comma separated SBHS API IPs here with ports
# (if hosted on specific ports)

CLIENT_VERSION = 3
#Client version supported by Django server

EXPERIMENT_LOGS_DIR = os.path.join(BASE_DIR, 'experiments')
#Path for user experiment folders on Django server.

SBHS_GLOBAL_LOG_DIR = os.path.join(BASE_DIR, 'log')
# Path for sbhs global log directory on Django server.


# Advance slot booking LIMIT for a day.
LIMIT = 2

WEBCAM_DIR = os.path.join(STATIC_ROOT, 'img/webcam/') if not IS_DEVELOPMENT \
                                                      else os.path.join(
                                                        BASE_DIR,
                                                        'static/img/webcam/'
                                                      )
WEBCAM_STATIC_DIR = 'img/webcam/'

