# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 13, 33, 24, 388022, tzinfo=utc), verbose_name='End time of a slot'),
        ),
    ]
