# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbhs', '0002_auto_20180807_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='booking',
        ),
        migrations.AddField(
            model_name='experiment',
            name='slot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sbhs.Slot'),
        ),
        migrations.AddField(
            model_name='slot',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
