# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs', '0002_auto_20180906_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 13, 36, 43, 319338, tzinfo=utc), verbose_name='End time of a slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 12, 41, 43, 319308, tzinfo=utc), verbose_name='Start time of a slot'),
        ),
    ]
