# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs', '0003_auto_20180906_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 10, 22, 15, 707069, tzinfo=utc), verbose_name='End time of a slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 9, 27, 15, 707039, tzinfo=utc), verbose_name='Start time of a slot'),
        ),
    ]
