# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs', '0004_auto_20180919_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 11, 4, 39, 103689, tzinfo=utc), verbose_name='End time of a slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 10, 10, 39, 103655, tzinfo=utc), verbose_name='Start time of a slot'),
        ),
    ]
