# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sbhs', '0005_auto_20180919_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='raspi_path',
            field=models.URLField(default='localhost:8000'),
        ),
        migrations.AddField(
            model_name='board',
            name='usb_path',
            field=models.URLField(default='/dev/ttyUSB0'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 13, 24, 14, 376575, tzinfo=utc), verbose_name='End time of a slot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 12, 29, 14, 376544, tzinfo=utc), verbose_name='Start time of a slot'),
        ),
    ]
